services:
  backend:
    command: litestar --app apps.backend.app.main:app run --host 0.0.0.0 --port 8000 --debug --reload --reload-dir apps/backend
    develop:
      watch:
        - action: sync
          path: ./apps/backend
          target: /workspace/apps/backend
          ignore:
            - __pycache__/

  worker:
    command: taskiq worker apps.backend.app.core.broker:broker apps.backend.app.features.document_parsing.tasks --workers 1 --max-async-tasks 1 --max-prefetch 1 --reload --reload-dir apps/backend
    develop:
      watch:
        - action: sync
          path: ./apps/backend
          target: /workspace/apps/backend
          ignore:
            - __pycache__/

  frontend:
    profiles: ["frontend"]
